language: php

dist: bionic

php:
  - 8.2

services:
  - docker

install:
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - make ci-with-coverage COVERAGE_FLAGS="--coverage-clover coverage.clover"
  - make install-php COMPOSER_FLAGS="--no-dev -q" # Remove dev dependencies to make sure PHPStan creates errors if prod code depends on dev classes
  - docker run -v $PWD:/app --rm registry.gitlab.com/fun-tech/fundraising-frontend-docker:stan analyse --level 9 --no-progress src/ # Can't use "make stan" because stan was removed

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
