language: php

php:
  - 7.4

sudo: false

services:
  - docker

install:
  - travis_retry make setup

script:
  - make ci

after_success:
  - vendor/bin/phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
