language: php

dist: bionic

php:
  - 8.2

services:
  - docker

install:
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - make ci-with-coverage COVERAGE_FLAGS="--coverage-clover coverage.clover"

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
